<?php

namespace App\DTO;

use App\Models\Task;
use App\Models\TaskType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * @extends BaseDTO<Task>
 */
class TaskDTO extends BaseDTO
{

    /**
     * @param string $name
     * @param string $description
     * @param string $address
     * @param string $customer
     * @param array<int> $taskType
     * @param float $latitude
     * @param float $longitude
     * @param int $state
     * @param string $expireAt
     * @param string|null $createdAt
     * @param string|null $updatedAt
     * @param WorkerDTO|null $worker
     * @param string|null $finishedAt
     * @param TaskDTO|null $parentTask
     */
    public function __construct(
        public string     $name,
        public string     $description,
        public string     $address,
        public string     $customer,
        public array      $taskType,
        public float      $latitude,
        public float      $longitude,
        public int        $state,
        public string     $expireAt ,
        public ?string    $createdAt = null,
        public ?string    $updatedAt = null,
        public ?WorkerDTO $worker = null,
        public ?string    $finishedAt = null,
        public ?TaskDTO   $parentTask = null,
        public ?int $id = null
    )
    {
       // $this->expireAt = Carbon::parse($expireAt);
    }

    /**
     * @param Task $model
     * @return static
     */
    static public function fromModel($model): static
    {
        return new static(

            $model->name,
            $model->description,
            $model->address,
            $model->customer,
            $model->types()->map(fn (TaskType $type) => $type->type)->toArray(),
            $model->latitude,
            $model->longitude,
            $model->state()->state,
            $model->created_at,
            $model->expired_at,
            $model->updated_at,
            $model->worker() ? WorkerDTO::fromModel($model->worker()) : null,
            $model->finishState() !== null ? $model->finishState()->created_at : null,
            $model->parentTask(),
            $model->id

        );
    }
    public static function fromJson($json): static|\stdClass
    {
        return parent::fromJson($json); // TODO: Change the autogenerated stub
    }

}
